
services:
  mysql:
    image: mysql:8.0
    container_name: mysql_ons
    environment:
      MYSQL_DATABASE: metastore_db_ons
      MYSQL_USER: ons
      MYSQL_PASSWORD: ons
      MYSQL_ROOT_PASSWORD: rootpassword
      TZ: "America/Sao_Paulo"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./mysqldata:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped
    networks:
      ons_network:
        ipv4_address: 172.30.0.10
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "127.0.0.1", "-u", "root", "-prootpassword" ]
      interval: 10s
      timeout: 5s
      retries: 20

volumes:
  mysqldata-data:

networks:
  ons_network:
    driver: bridge
    ipam:
      config:
        - subnet: "172.30.0.0/16"

